/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type ChainList string

// List of chainList
const (
	ETH_ChainList               ChainList = "eth"
	_0X1__ChainList             ChainList = "0x1"
	ROPSTEN_ChainList           ChainList = "ropsten"
	_0X3__ChainList             ChainList = "0x3"
	RINKEBY_ChainList           ChainList = "rinkeby"
	_0X4__ChainList             ChainList = "0x4"
	GOERLI_ChainList            ChainList = "goerli"
	_0X5__ChainList             ChainList = "0x5"
	KOVAN_ChainList             ChainList = "kovan"
	_0X2A__ChainList            ChainList = "0x2a"
	POLYGON_ChainList           ChainList = "polygon"
	_0X89__ChainList            ChainList = "0x89"
	MUMBAI_ChainList            ChainList = "mumbai"
	_0X13881__ChainList         ChainList = "0x13881"
	BSC_ChainList               ChainList = "bsc"
	_0X38__ChainList            ChainList = "0x38"
	BSC_TESTNET_ChainList       ChainList = "bsc testnet"
	_0X61__ChainList            ChainList = "0x61"
	AVALANCHE_ChainList         ChainList = "avalanche"
	_0XA86A__ChainList          ChainList = "0xa86a"
	AVALANCHE_TESTNET_ChainList ChainList = "avalanche testnet"
	_0XA869__ChainList          ChainList = "0xa869"
	FANTOM_ChainList            ChainList = "fantom"
	_0XFA__ChainList            ChainList = "0xfa"
)
