/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type EndpointWeights struct {
	// endpoint
	Endpoint string `json:"endpoint"`
	// The path to the endpoint
	Path string `json:"path"`
	// The number of hits the requests counts for ratelimiting
	RateLimitWeight string `json:"rateLimitWeight"`
	// The number of hits the requests counts for billing
	Price string `json:"price"`
}
